# Generated by Django 5.1.6 on 2025-03-10 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "level",
                    models.IntegerField(
                        default=2,
                        verbose_name=[(2, "Novice"), (4, "Middle"), (6, "Strong")],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        default="M",
                        max_length=1,
                        verbose_name=[("M", "Male"), ("F", "Female")],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ground_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "player_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="badminton.player",
                    ),
                ),
                ("won", models.IntegerField(default=0)),
                ("lost", models.IntegerField(default=0)),
                ("played", models.IntegerField(default=0)),
                ("rank", models.FloatField(default=0)),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="badminton.tournament",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("badminton.player",),
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_count", models.IntegerField(default=0)),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="badminton.tournament",
                    ),
                ),
                (
                    "a",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_a",
                        to="badminton.competitor",
                    ),
                ),
                (
                    "b",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_b",
                        to="badminton.competitor",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("a", "b"), name="unique_a_b")
                ],
            },
        ),
    ]
