# Generated by Django 5.1.6 on 2025-03-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badminton", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitor",
            name="is_playing",
            field=models.BooleanField(default=True),
        ),
    ]
