services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=true
    ports:
      - "8000:8000"
    volumes:
      - data_volume:/app/data
      - static_volume:/app/staticfiles

  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_volume:/home/app/web/static
    depends_on:
      - web
    networks:
      - python

volumes:
  static_volume:
  data_volume:

networks:
  python:
    driver: bridge
