services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=false
    volumes:
      - ./data:/app/data
      - static_volume:/app/staticfiles
    networks:
      - salad

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_volume:/home/app/web/static
    depends_on:
      - web
    networks:
      - salad
      - traefik-web # Connect to the Traefik network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-web"
      - "traefik.http.routers.salad.rule=Host(`salad.mintset.net`)"
      - "traefik.http.routers.salad.entrypoints=websecure"
      - "traefik.http.routers.salad.tls.certresolver=letsencrypt"
      - "traefik.http.services.salad.loadbalancer.server.port=8888" # The internal port your app listens on
      - "traefik.http.services.salad.loadbalancer.server.scheme=http"
volumes:
  static_volume:

networks:
  salad:
    driver: bridge
  traefik-web:
    external: true
