services:
  salad_backend_python:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=salad_backend_database
      - DB_PORT=5432
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - salad_backend
    depends_on:
      - salad_backend_database
  salad_backend_database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - salad_backend

  salad_backend_nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_volume:/home/app/web/static
    depends_on:
      - salad_backend_python
    networks:
      - salad_backend
      - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-web"
      - "traefik.http.routers.salad.rule=Host(`salad.mintset.net`)"
      - "traefik.http.routers.salad.entrypoints=websecure"
      - "traefik.http.routers.salad.tls.certresolver=letsencrypt"
      - "traefik.http.services.salad.loadbalancer.server.port=8888" # The internal port your app listens on
      - "traefik.http.services.salad.loadbalancer.server.scheme=http"

volumes:
  static_volume:
  postgres_data:

networks:
  salad_backend:
    driver: bridge
  traefik-web:
    external: true
