services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=true
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - data_volume:/app/data
      - static_volume:/app/staticfiles
    networks:
      - salad

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_volume:/home/app/web/static
    depends_on:
      - web
    networks:
      - salad
      - traefik-network # Connect to the Traefik network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cv.rule=Host(`salad.mintset.net`)"
      - "traefik.http.routers.cv.entrypoints=websecure"
      - "traefik.http.routers.cv.tls.certresolver=letsencrypt"
      - "traefik.http.services.cv.loadbalancer.server.port=8888" # The internal port your app listens on
volumes:
  static_volume:
  data_volume:

networks:
  salad:
    driver: bridge
  traefik-network:
    external: true
